-- CreateEnum
CREATE TYPE "RewardStatus" AS ENUM ('active', 'inactive');

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "email_verified_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "password" TEXT NOT NULL,
    "phone" TEXT,
    "SFDC_ID" TEXT,
    "AccountId" TEXT,
    "ContactId" TEXT,
    "is_work_from_home" BOOLEAN NOT NULL DEFAULT false,
    "is_wfh_cc_email" BOOLEAN NOT NULL DEFAULT false,
    "status" INTEGER NOT NULL DEFAULT 1,
    "profile_id" TEXT,
    "google_id" TEXT,
    "o365_id" TEXT,
    "old_last_login" TIMESTAMP(3),
    "last_login" TIMESTAMP(3),
    "account_address_id" TIMESTAMP(3),
    "remember_token" TEXT NOT NULL,
    "login_from_super_admin" INTEGER NOT NULL DEFAULT 0,
    "source" TEXT,
    "approval_lot_id" TEXT,
    "is_schedule_approval" BOOLEAN NOT NULL DEFAULT false,
    "my_reward_active" "RewardStatus" NOT NULL DEFAULT 'inactive',
    "create_source" TEXT,
    "CreatedDate" TIMESTAMP(3),
    "LastModifiedDate" TIMESTAMP(3),
    "created_by" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Contact" (
    "id" SERIAL NOT NULL,
    "SFDC_ID" VARCHAR(255),
    "update_map_history_id" BIGINT,
    "insert_map_history_id" BIGINT,
    "IsDeleted" BOOLEAN,
    "MasterRecordId" TEXT,
    "AccountId" VARCHAR(255),
    "LastName" VARCHAR(255),
    "FirstName" VARCHAR(255),
    "Salutation" TEXT,
    "MiddleName" TEXT,
    "Suffix" TEXT,
    "Name" TEXT,
    "RecordTypeId" TEXT,
    "OtherStreet" TEXT,
    "OtherCity" TEXT,
    "OtherState" TEXT,
    "OtherPostalCode" TEXT,
    "OtherCountry" TEXT,
    "OtherLatitude" DECIMAL(15,3),
    "OtherLongitude" DECIMAL(15,3),
    "OtherGeocodeAccuracy" TEXT,
    "OtherAddress" TEXT,
    "MailingStreet" TEXT,
    "MailingCity" TEXT,
    "MailingState" TEXT,
    "MailingPostalCode" TEXT,
    "MailingCountry" TEXT,
    "MailingLatitude" DECIMAL(15,3),
    "MailingLongitude" DECIMAL(15,3),
    "MailingGeocodeAccuracy" TEXT,
    "MailingAddress" TEXT,
    "Phone" TEXT,
    "Fax" TEXT,
    "MobilePhone" TEXT,
    "HomePhone" TEXT,
    "OtherPhone" TEXT,
    "ReportsToId" TEXT,
    "Email" VARCHAR(255),
    "Title" TEXT,
    "Department" TEXT,
    "Description" TEXT,
    "OwnerId" TEXT,
    "CreatedDate" TIMESTAMP(3),
    "CreatedById" TEXT,
    "LastModifiedDate" TIMESTAMP(3),
    "LastModifiedById" TEXT,
    "SystemModstamp" TIMESTAMP(3),
    "LastActivityDate" DATE,
    "LastCURequestDate" TIMESTAMP(3),
    "LastCUUpdateDate" TIMESTAMP(3),
    "LastViewedDate" TIMESTAMP(3),
    "LastReferencedDate" TIMESTAMP(3),
    "EmailBouncedReason" TEXT,
    "EmailBouncedDate" TIMESTAMP(3),
    "IsEmailBounced" BOOLEAN,
    "PhotoUrl" TEXT,
    "Jigsaw" TEXT,
    "JigsawContactId" TEXT,
    "IndividualId" TEXT,
    "Account_level_Marketing_Suppression__c" TEXT,
    "rh2__Currency_Test__c" DECIMAL(15,2),
    "rh2__Describe__c" TEXT,
    "rh2__Formula_Test__c" DECIMAL(15,2),
    "rh2__Integer_Test__c" DECIMAL(3,0),
    "Email_2__c" TEXT,
    "Source__c" TEXT,
    "Low_Grade_Title__c" BOOLEAN,
    "Job_Function__c" TEXT,
    "Technology_Responsibilities__c" TEXT,
    "Is_Recycling__c" BOOLEAN DEFAULT false,
    "Warm__c" TEXT,
    "Outreach_Current_Sequence_Name__c" TEXT,
    "LinkedIn__c" TEXT,
    "Street_2__c" TEXT,
    "Staged_Changed_At__c" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "Outreach_Initial_Sequence_Name__c" TEXT,
    "RingLead_Archive__c" TEXT,
    "ContactOwnerCheck__c" BOOLEAN DEFAULT false,
    "Apollo_Contact_ID__c" TEXT,
    "Apollo_Account_ID__c" TEXT,
    "Quickmail_Update_DATE__c" DATE,
    "Marketing_Suppression_Trigger__c" BOOLEAN DEFAULT false,
    "Have_Open_Tasks__c" BOOLEAN DEFAULT false,
    "IsWarm__c" BOOLEAN DEFAULT false,
    "Imported_to_emailer_within_last_30_days__c" BOOLEAN DEFAULT false,
    "Last_Quickmail_Import__c" DATE,
    "Has_Open_Lot__c" BOOLEAN DEFAULT false,
    "Has_Open_Opportunity__c" BOOLEAN DEFAULT false,
    "Completed_Marketing_Segment__c" TEXT,
    "Most_Recent_Marketing_Action__c" DATE,
    "Phone_US__c" TEXT,
    "Referred_By__c" TEXT,
    "Merged_DateTime__c" TIMESTAMP(3),
    "Email_3__c" TEXT,
    "RingLead_Score__c" DECIMAL(5,2),
    "Business_Unit__c" TEXT,
    "Flag_for_Deletion__c" BOOLEAN,
    "Marketing_Email_Status__c" TEXT,
    "Owner_Type__c" TEXT,
    "Primary_Vendor_Contact__c" BOOLEAN,
    "DuplicateEmails__c" BOOLEAN,
    "Status__c" TEXT,
    "Buyer_Category__c" TEXT,
    "Customer_Portal_Access__c" BOOLEAN,
    "rcsfl__SMS_Number__c" TEXT,
    "rcsfl__SendSMS__c" TEXT,
    "DOZISF__ZoomInfo_Company_ID__c" TEXT,
    "DOZISF__ZoomInfo_First_Updated__c" TIMESTAMP(3),
    "DOZISF__ZoomInfo_Id__c" TEXT,
    "DOZISF__ZoomInfo_Last_Updated__c" TIMESTAMP(3),
    "Favorite_Buyer__c" BOOLEAN,
    "Last_Login__c" TIMESTAMP(3),
    "IsCustomer__c" BOOLEAN,
    "Contact_Portal_Url__c" TEXT,
    "Date_Time_Interested__c" TIMESTAMP(3),
    "Date_Time_Replied__c" TIMESTAMP(3),
    "Title_Score_1__c" DECIMAL(15,2),
    "Title_All_Caps__c" TEXT,
    "Title_Score_2__c" DECIMAL(15,2),
    "Title_Score_3__c" DECIMAL(15,2),
    "Title_Score__c" DECIMAL(15,2),
    "Quickmail_Journey__c" TEXT,
    "Last_Quickmail_Update__c" TIMESTAMP(3),
    "Persona__c" TEXT,
    "Quickmail_Tags__c" TEXT,
    "Last_Quickmail_Checkpoint__c" TEXT,
    "QuickmailProspect__c" BOOLEAN,
    "Outreach_Stage__c" TEXT,
    "is_testing" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "Contact_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Accounts" (
    "id" SERIAL NOT NULL,
    "SFDC_ID" VARCHAR(255),
    "update_map_history_id" BIGINT,
    "insert_map_history_id" BIGINT,
    "IsDeleted" BOOLEAN DEFAULT false,
    "MasterRecordId" TEXT,
    "Name" VARCHAR(255),
    "Type" TEXT,
    "ParentId" TEXT,
    "BillingStreet" TEXT,
    "BillingCity" TEXT,
    "BillingState" TEXT,
    "BillingPostalCode" TEXT,
    "BillingCountry" TEXT,
    "BillingLatitude" DECIMAL(15,3),
    "BillingLongitude" DECIMAL(15,3),
    "BillingGeocodeAccuracy" TEXT,
    "BillingAddress" VARCHAR(255),
    "ShippingStreet" TEXT,
    "ShippingCity" TEXT,
    "ShippingState" TEXT,
    "ShippingPostalCode" TEXT,
    "ShippingCountry" TEXT,
    "ShippingLatitude" DECIMAL(15,3),
    "ShippingLongitude" DECIMAL(15,3),
    "ShippingGeocodeAccuracy" TEXT,
    "ShippingAddress" TEXT,
    "Phone" TEXT,
    "Website" TEXT,
    "PhotoUrl" TEXT,
    "Industry" TEXT,
    "NumberOfEmployees" INTEGER,
    "Description" TEXT,
    "OwnerId" TEXT,
    "CreatedDate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "CreatedById" TEXT,
    "LastModifiedDate" TIMESTAMP(3),
    "LastModifiedById" TEXT,
    "SystemModstamp" TIMESTAMP(3),
    "LastActivityDate" TIMESTAMP(3),
    "LastViewedDate" TIMESTAMP(3),
    "LastReferencedDate" TIMESTAMP(3),
    "IsCustomerPortal" BOOLEAN DEFAULT false,
    "Jigsaw" TEXT,
    "JigsawCompanyId" TEXT,
    "AccountSource" TEXT,
    "SicDesc" TEXT,
    "Domain__c" TEXT,
    "Batch_Size__c" DECIMAL(15,2),
    "IT_Employees_old__c" DECIMAL(18,0),
    "Fortune_Rank__c" DECIMAL(18,0),
    "IT_Budget_Million__c" DECIMAL(18,0),
    "Number_of_Contacts__c" DECIMAL(5,0),
    "Revenue__c" DECIMAL(18,0),
    "Marketing_Suppression__c" TEXT,
    "First_Sender_and_Date__c" TEXT,
    "Suppression_Reason__c" TEXT,
    "Active_Contacts__c" DECIMAL(4,0),
    "AccountOwnerCheck__c" BOOLEAN DEFAULT false,
    "Total_Available_Credits__c" DECIMAL(15,3),
    "Apollo_Account_ID__c" TEXT,
    "Suppressed_By__c" TEXT,
    "Suppression_Date__c" TIMESTAMP(3),
    "Hard_Drive_Parent_Asset_Required__c" BOOLEAN,
    "Trimmed_Website__c" TEXT,
    "Lot_Last_Created__c" TIMESTAMP(3),
    "Opportunity_Last_Created__c" TIMESTAMP(3),
    "Internal_Brand__c" TEXT,
    "Phone_US__c" TEXT,
    "Total_Opportunities__c" DECIMAL(15,3),
    "Won_Opportunities__c" DECIMAL(15,3),
    "Terms__c" TEXT,
    "RingLead_Archive__c" TEXT,
    "Merged_DateTime__c" TIMESTAMP(3),
    "Outreach_URL__c" TEXT,
    "Notification_Emails__c" TEXT,
    "Payment_Past_Due__c" BOOLEAN,
    "Notes__c" TEXT,
    "Razor_Customer_ID__c" TEXT,
    "Razor_Needs_Updated__c" BOOLEAN,
    "RingLead_Score__c" DECIMAL(4,0),
    "DOZISF__ZoomInfo_First_Updated__c" TIMESTAMP(3),
    "DOZISF__ZoomInfo_Id__c" TEXT,
    "DOZISF__ZoomInfo_Last_Updated__c" TIMESTAMP(3),
    "Work_Instruction__c" TEXT,
    "Shipping_Vendor__c" BOOLEAN,
    "Signed_MSA__c" BOOLEAN,
    "Coverage_Area_Shipping_Vendors__c" TEXT,
    "Primary_Contact__c" TEXT,
    "Services_Available__c" TEXT,
    "CustomerPortalAccess__c" BOOLEAN,
    "WFHCode__c" TEXT,
    "WFHUrl__c" TEXT,
    "Only_Process_In_House__c" BOOLEAN,
    "ZoomInfo_URL__c" TEXT,
    "Defunct__c" TEXT,
    "Service_Vendor__c" BOOLEAN,
    "Rolling_Balance__c" BOOLEAN,
    "Notes_for_Settlements__c" TEXT,
    "Compliance_Agreement_Signed__c" BOOLEAN,
    "Downstream_Shipping__c" TEXT,
    "Size_Category_V2__c" TEXT,
    "Default_Customer_Expectation__c" TEXT,
    "To_Trigger_Update__c" TEXT,
    "Account_ID_Text__c" TEXT,
    "myTime" VARCHAR(255),
    "is_testing" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "Accounts_pkey" PRIMARY KEY ("id")
);
