const ruleSet = {
  name: 'ruleSet',
  tables: [
    // Accounts table
    {
      name: 'Accounts',
      displayPublic: true,
      fields: [
        {
          name: 'id',
          type: 'string',
          displayPublic: false,
          required: false,
        },
        {
          name: 'SFDC_ID',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'update_map_history_id',
          type: 'BigInt',
          displayPublic: true,
          required: false,
        },
        {
          name: 'insert_map_history_id',
          type: 'BigInt',
          displayPublic: true,
          required: false,
        },
        {
          name: 'IsDeleted',
          type: 'Boolean',
          displayPublic: true,
          required: false,
          default: false,
        },
        {
          name: 'MasterRecordId',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'name',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Type',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ParentId',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingStreet',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingCity',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingState',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingPostalCode',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingCountry',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingLatitude',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingLongitude',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingGeocodeAccuracy',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'BillingAddress',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingStreet',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingCity',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingState',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingPostalCode',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingCountry',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingLatitude',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingLongitude',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingGeocodeAccuracy',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ShippingAddress',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Phone',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Website',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'PhotoUrl',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Industry',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'NumberOfEmployees',
          type: 'Int',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Description',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'OwnerId',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'CreatedDate',
          type: 'DateTime',
          displayPublic: true,
          required: false,
          default: 'now()',
        },
        {
          name: 'CreatedById',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastModifiedDate',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastModifiedById',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'SystemModstamp',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastActivityDate',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastViewedDate',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastReferencedDate',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'IsCustomerPortal',
          type: 'Boolean',
          displayPublic: true,
          required: false,
          default: false,
        },
        {
          name: 'Jigsaw',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'JigsawCompanyId',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'AccountSource',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'SicDesc',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Domain__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Batch_Size__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'IT_Employees_old__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Fortune_Rank__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'IT_Budget_Million__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Number_of_Contacts__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Revenue__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Marketing_Suppression__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'First_Sender_and_Date__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Suppression_Reason__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Active_Contacts__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'AccountOwnerCheck__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
          default: false,
        },
        {
          name: 'Total_Available_Credits__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Apollo_Account_ID__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Suppressed_By__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Suppression_Date__c',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          displayPublic: true,
          name: 'Hard_Drive_Parent_Asset',
          type: 'Boolean',
          required: false,
        },
        {
          name: 'Trimmed_Website__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Lot_Last_Created__c',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Opportunity_Last_Created__c',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Internal_Brand__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Phone_US__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Total_Opportunities__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Won_Opportunities__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Terms__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'RingLead_Archive__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Merged_DateTime__c',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Outreach_URL__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Notification_Emails__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Payment_Past_Due__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Notes__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Razor_Customer_ID__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Razor_Needs_Updated__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'RingLead_Score__c',
          type: 'Decimal',
          displayPublic: true,
          required: false,
        },
        {
          name: 'DOZISF__ZoomInfo_First_Updated__c',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'DOZISF__ZoomInfo_Id__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'DOZISF__ZoomInfo_Last_Updated__c',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Work_Instruction__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Shipping_Vendor__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Signed_MSA__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Coverage_Area_Shipping_Vendors__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Primary_Contact__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Services_Available__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'CustomerPortalAccess__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'WFHCode__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'WFHUrl__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Only_Process_In_House__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ZoomInfo_URL__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Defunct__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Service_Vendor__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Rolling_Balance__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Notes_for_Settlements__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Compliance_Agreement_Signed__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Downstream_Shipping__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Size_Category_V2__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Default_Customer_Expectation__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'To_Trigger_Update__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Account_ID_Text__c',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'myTime',
          type: 'string',
          displayPublic: true,
          required: false,
        },
        {
          name: 'is_testing',
          type: 'Int',
          displayPublic: true,
          required: false,
          default: 0,
        },
        {
          name: 'created_at',
          type: 'DateTime',
          displayPublic: true,
          required: false,
          default: new Date(),
        },
        {
          name: 'updated_at',
          type: 'DateTime',
          displayPublic: true,
          required: false,
          default: new Date(),
          updatedAt: true,
        },
        {
          name: 'deleted_at',
          type: 'DateTime',
          displayPublic: true,
          required: false,
        },
      ],
    },
    // Contact table
    {
      name: 'Contacts',
      displayPublic: true,
      fields: [
        {
          name: 'id',
          type: 'Int',
          displayPublic: true,
          required: false,
        },
        {
          name: 'SFDC_ID',
          type: 'String',
          nullable: true,
          length: 255,
          displayPublic: true,
          required: false,
        },
        {
          name: 'update_map_history_id',
          type: 'BigInt',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'insert_map_history_id',
          type: 'BigInt',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'IsDeleted',
          type: 'Boolean',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MasterRecordId',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'AccountId',
          type: 'String',
          nullable: true,
          length: 255,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastName',
          type: 'String',
          nullable: true,
          length: 255,
          displayPublic: true,
          required: false,
        },
        {
          name: 'FirstName',
          type: 'String',
          nullable: true,
          length: 255,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Salutation',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MiddleName',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Suffix',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Name',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'RecordTypeId',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherStreet',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherCity',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherState',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherPostalCode',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherCountry',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherLatitude',
          type: 'Decimal',
          precision: 15,
          scale: 3,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherLongitude',
          type: 'Decimal',
          precision: 15,
          scale: 3,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherGeocodeAccuracy',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherAddress',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingStreet',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingCity',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingState',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingPostalCode',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingCountry',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingLatitude',
          type: 'Decimal',
          precision: 15,
          scale: 3,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingLongitude',
          type: 'Decimal',
          precision: 15,
          scale: 3,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingGeocodeAccuracy',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MailingAddress',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Phone',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Fax',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'MobilePhone',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'HomePhone',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OtherPhone',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'ReportsToId',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Email',
          type: 'String',
          nullable: true,
          length: 255,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Title',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Department',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Description',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'OwnerId',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'CreatedDate',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'CreatedById',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastModifiedDate',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastModifiedById',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'SystemModstamp',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastActivityDate',
          type: 'DateTime',
          dateOnly: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastCURequestDate',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastCUUpdateDate',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastViewedDate',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LastReferencedDate',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'EmailBouncedReason',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'EmailBouncedDate',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'IsEmailBounced',
          type: 'Boolean',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'PhotoUrl',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Jigsaw',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'JigsawContactId',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'IndividualId',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Account_level_Marketing_Suppression__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'rh2__Currency_Test__c',
          type: 'Decimal',
          precision: 15,
          scale: 2,
          displayPublic: true,
          required: false,
        },
        {
          name: 'rh2__Describe__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'rh2__Formula_Test__c',
          type: 'Decimal',
          precision: 15,
          scale: 2,
          displayPublic: true,
          required: false,
        },
        {
          name: 'rh2__Integer_Test__c',
          type: 'Decimal',
          precision: 3,
          scale: 0,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Email_2__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Source__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Low_Grade_Title__c',
          type: 'Boolean',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Job_Function__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Technology_Responsibilities__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Is_Recycling__c',
          type: 'Boolean',
          default: false,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Warm__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Outreach_Current_Sequence_Name__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'LinkedIn__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Street_2__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Staged_Changed_At__c',
          type: 'DateTime',
          default: 'now()',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Outreach_Initial_Sequence_Name__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'RingLead_Archive__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'ContactOwnerCheck__c',
          type: 'Boolean',
          default: false,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Apollo_Contact_ID__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Apollo_Account_ID__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Quickmail_Update_DATE__c',
          type: 'DateTime',
          dateOnly: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Marketing_Suppression_Trigger__c',
          type: 'Boolean',
          default: false,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Have_Open_Tasks__c',
          type: 'Boolean',
          default: false,
          displayPublic: true,
          required: false,
        },
        {
          name: 'IsWarm__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
          default: false,
        },
        {
          name: 'Imported_to_emailer_within_last_30_days__c',
          type: 'Boolean',
          default: false,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Last_Quickmail_Import__c',
          type: 'DateTime',
          dateOnly: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Has_Open_Lot__c',
          type: 'Boolean',
          default: false,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Has_Open_Opportunity__c',
          type: 'Boolean',
          default: false,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Completed_Marketing_Segment__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Most_Recent_Marketing_Action__c',
          type: 'DateTime',
          dateOnly: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Phone_US__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Referred_By__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Merged_DateTime__c',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Email_3__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'RingLead_Score__c',
          type: 'Decimal',
          precision: 5,
          displayPublic: true,
          required: false,
          scale: 2,
        },
        {
          name: 'Business_Unit__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Flag_for_Deletion__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Marketing_Email_Status__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Owner_Type__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Primary_Vendor_Contact__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'DuplicateEmails__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Status__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Buyer_Category__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Customer_Portal_Access__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'rcsfl__SMS_Number__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'rcsfl__SendSMS__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'DOZISF__ZoomInfo_Company_ID__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'DOZISF__ZoomInfo_First_Updated__c',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'DOZISF__ZoomInfo_Id__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'DOZISF__ZoomInfo_Last_Updated__c',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Favorite_Buyer__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Last_Login__c',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'IsCustomer__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Contact_Portal_Url__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Date_Time_Interested__c',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Date_Time_Replied__c',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Title_Score_1__c',
          type: 'Decimal',
          precision: 15,
          scale: 2,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Title_All_Caps__c',
          type: 'String',
          displayPublic: true,
          required: false,
          nullable: true,
        },
        {
          name: 'Title_Score_2__c',
          type: 'Decimal',
          precision: 15,
          scale: 2,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Title_Score_3__c',
          type: 'Decimal',
          precision: 15,
          displayPublic: true,
          required: false,
          scale: 2,
        },
        {
          name: 'Title_Score__c',
          type: 'Decimal',
          precision: 15,
          scale: 2,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Quickmail_Journey__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Last_Quickmail_Update__c',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Persona__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Quickmail_Tags__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'Last_Quickmail_Checkpoint__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'QuickmailProspect__c',
          type: 'Boolean',
          displayPublic: true,
          required: false,
        },
        {
          name: 'Outreach_Stage__c',
          type: 'String',
          nullable: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'is_testing',
          type: 'Int',
          default: 0,
          displayPublic: true,
          required: false,
        },
        {
          name: 'created_at',
          type: 'DateTime',
          default: 'now()',
          displayPublic: true,
          required: false,
        },
        {
          name: 'updated_at',
          type: 'DateTime',
          default: 'now()',
          updatedAt: true,
          displayPublic: true,
          required: false,
        },
        {
          name: 'deleted_at',
          type: 'DateTime',
          nullable: true,
          displayPublic: true,
          required: false,
        },
      ],
      relationShips: [
        {
          name: 'account',
          sourceTable: 'Contacts',
          type: 'many-to-one',
          sourceTableField: 'AccountId',
          relationType: 'parent',
          targetTable: 'Accounts',
          targetTableField: 'Id',
        },
      ],
    },
    // User table
    {
      name: 'Users',
      displayPublic: false,
      fields: [
        {
          name: 'id',
          type: 'Int',
          displayPublic: true,
          required: false,
        },
        {
          name: 'name',
          type: 'String',
          displayPublic: true,
          required: false,
        },
        {
          name: 'email',
          type: 'String',
          displayPublic: true,
          required: false,
        },
        {
          name: 'email_verified_at',
          type: 'DateTime',
          default: 'now()',
        },
        {
          name: 'password',
          type: 'String',
          displayPublic: true,
          required: false,
        },
        {
          name: 'phone',
          type: 'String',
          displayPublic: true,
          required: false,
        },
        {
          name: 'SFDC_ID',
          type: 'String',
          displayPublic: true,
          required: false,
        },
        {
          name: 'AccountId',
          type: 'String',
          displayPublic: true,
          required: false,
        },
        {
          name: 'ContactId',
          type: 'String',
          displayPublic: true,
          required: false,
        },
        {
          name: 'is_work_from_home',
          type: 'Boolean',
          default: false,
        },
        {
          name: 'is_wfh_cc_email',
          type: 'Boolean',
          default: false,
        },
        {
          name: 'status',
          type: 'Int',
          default: 1,
        },
        {
          name: 'profile_id',
          type: 'String',
          displayPublic: true,
          required: false,
        },
        {
          name: 'google_id',
          type: 'String',
          required: false,
        },
        {
          name: 'o365_id',
          type: 'String',
          required: false,
        },
        {
          name: 'old_last_login',
          type: 'DateTime',
          required: false,
        },
        {
          name: 'last_login',
          type: 'DateTime',
          required: false,
        },
        {
          name: 'account_address_id',
          type: 'DateTime',
          required: false,
        },
        {
          name: 'remember_token',
          type: 'String',
          required: false,
        },
        {
          name: 'login_from_super_admin',
          type: 'Int',
          default: 0,
        },
        {
          name: 'source',
          type: 'String',
          required: false,
        },
        {
          name: 'approval_lot_id',
          type: 'String',
          required: false,
        },
        {
          name: 'is_schedule_approval',
          type: 'Boolean',
          default: 'false',
        },
        {
          name: 'my_reward_active',
          type: 'RewardStatus',
          default: 'inactive',
        },
        {
          name: 'create_source',
          type: 'String',
          required: false,
        },
        {
          name: 'CreatedDate',
          type: 'DateTime',
          required: false,
        },
        {
          name: 'LastModifiedDate',
          type: 'DateTime',
          required: false,
        },
        {
          name: 'created_by',
          type: 'Int',
          default: 0,
        },
        {
          name: 'created_at',
          type: 'DateTime',
          default: new Date(),
        },
        {
          name: 'updated_at',
          type: 'DateTime',
          default: new Date(),
          updatedAt: true,
        },
        {
          name: 'deleted_at',
          type: 'DateTime',
          required: false,
        },
      ],
      relationShips: {
        Accounts: {
          sourceTable: 'User',
          type: 'many-to-one',
          sourceTableField: 'AccountId',
          relationType: 'parent',
        },
      },
    },
  ],
};

// export const fetchUploadInfo = async (tablee: string) => {
//     const getRuleSet = ruleSet.tables.find((table) => table.name === tablee)
//     const tableFields = (getRuleSet.fields).map((item: { name: any }) => item.name)
//     const relationship = getRuleSet.relationShips && getRuleSet.relationShips.Accounts;

//     console.log("result----[ line 1446 ]----->", relationship)
//     return tableFields
// }
export const fetchUploadInfo = async (tablee: string) => {
  const result = [];

  for (const table of ruleSet.tables) {
    // Extracting the table name
    const tableName = table.name;

    // Extracting the fields array from the table
    const fields = table.fields || [];

    // Looping through each field in the fields array
    for (const field of fields) {
      // Extracting the field name
      const fieldName = field.name;

      // Creating an object in the desired format and adding it to the result array
      result.push({
        table: tableName,
        name: fieldName,
      });
    }
  }
  return result;
};
export const fetchTableName = async () => {
  const tableNames = ruleSet.tables
    .filter((table) => table.displayPublic === true)
    .map((table) => table.name);
  return tableNames;
};

export const fetchAllRules = () => {
  return ruleSet;
};
