name: Build and deploy Node.js app to Azure Web App - contactwindos

on:
  push:
    branches:
      - main
    paths:
      - '**/*' # Trigger only when any file changes

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x' # Updated to a commonly used LTS version

      - name: npm install, build, and test
        run: |          
          npm install --save @azure/identity          
          npm run build --if-present
          
      - name: 'Deploy to Azure Web App'
       
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
            app-name: 'contactwindos'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8083AA67A21B4C69B7D87D7CEF6A8A2E }}
            package: .

  
